FROM python:3.10-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r Requirements.txt
EXPOSE 8080
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8080", "--server.address=0.0.0.0"]